apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  replicas: 1
  strategy:
    type: Recreate # Important: only 1 pod can use the USB at a time
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: usb
          mountPath: /dev/ttyUSB0
        - name: data
          mountPath: /app/data
        - name: zigbee2mqtt-config
          mountPath: /app/data/configuration.yaml
          subPath: configuration.yml
      volumes:
      - name: usb
        hostPath:
          path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_2aeb408cd13aec11b15a9e957a0af07f-if00-port0
          type: CharDevice
      - name: data
        hostPath:
          path: /opt/docker-data/zigbee2mqtt
          type: DirectoryOrCreate
      - name: zigbee2mqtt-config
        configMap:
          name: zigbee2mqtt-config