apiVersion: trafik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt-ingress
  namespace: home-automation
spec:
  tls:
  - hosts:
    - z2m.cluster.marcodoes.tech
    secretName: zigbee2mqtt-tls
  rules:
  - host: z2m.cluster.marcodoes.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zigbee2mqtt
            port:
              number: 8080