apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt-ingress
  namespace: home-automation
  annotations:
    external-dns.alpha.kubernetes.io/hostname: z2m.cluster.marcodoes.tech
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - z2m.cluster.marcodoes.tech
    secretName: zigbee2mqtt-tls
  rules:
  - host: z2m.cluster.marcodoes.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zigbee2mqtt
            port:
              number: 8080