apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.43.0.10 # The standard K3s CoreDNS IP
        searches:
          - home-automation.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-logs
          mountPath: /mosquitto/log
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        hostPath:
          path: /opt/docker-data/mosquitto/data
          type: DirectoryOrCreate
      - name: mosquitto-logs
        hostPath:
          path: /opt/docker-data/mosquitto/log
          type: DirectoryOrCreate
