apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-automation
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ha.cluster.marcodoes.tech
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - ha.cluster.marcodoes.tech
    secretName: home-assistant-tls
  rules:
  - host: ha.cluster.marcodoes.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123